name: .NET Android

on:
  workflow_dispatch:
    inputs:
      verbosity:
        description: 'Verbosity'
        required: true
        default: 'minimal'
        type: choice
        options:
          - quiet
          - minimal
          - normal
          - detailed
      configuration:
        description: 'Verbosity'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release
jobs:
  build:
    runs-on: macos-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Project_Folder: src/quickstart/DotnetAndroid.MapboxQs
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET 8.0
    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.200

    - name: Install Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        java-package: jdk # optional (jdk or jre) - defaults to jdk
        
    # Install .NET Android workload
    - name: Install .NET Android workload
      run: dotnet workload install android

    # Clean
    - name: Clean the application
      run: |
        cd $Project_Folder
        dotnet clean -c $Configuration
      env:
        Configuration: ${{ inputs.configuration }} 

    # Build application
    - name: Build the application
      run: |
        cd $Project_Folder
        echo "Home: $HOME"
        dotnet build -c $Configuration -v $Verbosity -p:JavaSdkDirectory="$JAVA_HOME"
        ls -ld ~/.gradle
      env:
        Configuration: ${{ inputs.configuration }} 
        Verbosity: ${{ inputs.verbosity }}